### ISSUE TITLE
btConvexHullShape' get_vertex method is flawed

### ISSUE THREAD

**Issue by jf---** [klumhru/boost-python-bullet#4]
In [23]: sp = bullet.btConvexHullShape()

In [24]: sp.add_point(1)

----> 1 sp.get_vertex(1)

ArgumentError: Python argument types in
    btPolyhedralConvexShape.get_vertex(btConvexHullShape, int)
did not match C++ signature:
    get_vertex(btPolyhedralConvexShape {lvalue}, int, btVector3 {lvalue})

In [34]:

**Comment by klumhru** [comment]
This will be resolved when tests for shapes shape up. I'm doing all of the shapes in one run, and then I'll do btRigidBody which is neccesary for tests of shapes (and vice versa). The tests will reveal more bugs but that's what they're for after all. I won't add the shapes to the completed list until the tests are done.
