### ISSUE TITLE
numpy support

### ISSUE THREAD

**Issue by jf---** [klumhru/boost-python-bullet#5]
I know this is really early... 
BUT... numpy support could be really sweet, since this would allow to transfer meshes ( the verts and corresponding indices ) really quickly, and in a way that is congruent with many python project...

Again, one for the ideas list ;)

**Comment by klumhru** [comment]
Yep, I looked at numpy when I started for array support specifically. The
striding interfaces which are required for mesh transfers could require
this.

**Comment by jf---** [comment]
Nice. Perfect for integration...

**Comment by klumhru** [comment]
This will be one of several possible integration modules, but will not be part of the core project. Added to roadmap, closed as answered.
