### ISSUE TITLE
request: btGjkPairDetector

### ISSUE THREAD

**Issue by jf---** [klumhru/boost-python-bullet#6]
A really sweet class in bullet is btGjkPairDetector.
It comes with a method getClosestPoints which returns the closest distance of 2 shapes. 

Are there plans to include wrapping on this class?

[1] http://bulletphysics.org/Bullet/BulletFull/classbtGjkPairDetector.html

**Comment by klumhru** [comment]
Definately. The Collision and Dynamics classes will mostly be implemented,
especially the callback classes and collision interfaces (actions, etc).

**Comment by jf---** [comment]
Terrific, thanks.

**Comment by klumhru** [comment]
These features are on the roadmap and will be implemented in due time. Closing issue as answered.
